version: '3.9'

volumes:
  db:
  wordpress:

services:
  node:
    container_name: node
    build:
      context: ../images/node
      dockerfile: node.dockerfile
      target: ${ENV?}
      args:
        - NODE_VERSION=${NODE_VERSION?}
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
    volumes:
      - ${CODE_PATH_HOST?}:/project

  app:
    container_name: app
    build:
      context: ../
      dockerfile: ./images/php/app/app.dockerfile
      target: ${ENV?}
      args:
        - PHP_VERSION=${PHP_VERSION?}
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - COMPOSER_VERSION=${COMPOSER_VERSION?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
        - APP_CODE_PATH=${CODE_PATH_CONTAINER?}
        - ENV=${ENV?}
    volumes:
      - ${CODE_PATH_HOST?}:${CODE_PATH_CONTAINER?}
    secrets:
      - source: composer_auth_json
        target: /home/${APP_USER_NAME?}/.composer/auth.json

  db:
    container_name: db
    image: ${DB_IMAGE?}
    environment:
      MYSQL_DATABASE: ${DB_NAME:-snicco_enterprise}
      MYSQL_USER: ${DB_USER:-snicco}
      MYSQL_PASSWORD: ${DB_PASSWORD:-snicco}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-snicco_root}
    healthcheck:
      test: [ "CMD-SHELL", "mysql ${DB_NAME:-snicco_enterprise} -u${DB_USER:-snicco} -p${DB_PASSWORD:-snicco} -e 'SELECT 1;'  || exit 1" ]
      interval: 0.1s
      retries: 20

  wp:
    container_name: wp
    build:
      context: ${CODE_PATH_HOST}
      dockerfile: ./.docker/images/wordpress/wordpress.dockerfile
      args:
        - WP_VERSION=${WP_VERSION?}
        - WP_CLI_VERSION=${WP_CLI_VERSION?}
        - PHP_VERSION=${PHP_VERSION?}
        - ALPINE_VERSION=${ALPINE_VERSION?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
        - APP_CODE_PATH=${CODE_PATH_CONTAINER?}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER:-snicco}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-snicco}
      WORDPRESS_DB_NAME: ${DB_NAME:-snicco_enterprise}
    volumes:
      - wordpress:${CODE_PATH_CONTAINER?}
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    build:
      context:  ../images/nginx
      dockerfile: nginx.dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION?}
        - APP_GROUP_ID=${APP_GROUP_ID?}
        - APP_GROUP_NAME=${APP_GROUP_NAME?}
        - APP_USER_ID=${APP_USER_ID?}
        - APP_USER_NAME=${APP_USER_NAME?}
        - APP_CODE_PATH=${CODE_PATH_CONTAINER?}
    depends_on:
      - wp
    volumes:
      - wordpress:${CODE_PATH_CONTAINER?}

secrets:
  composer_auth_json:
    file: ${COMPOSER_AUTH_JSON_PATH}
