version: '3.9'

services:
  app:
    volumes:
      # We need to persist the host composer cache with the docker container.
      # Otherwise, each composer update will be extremely slow.
      - ${COMPOSER_CACHE_PATH?}:/home/${APP_USER_NAME?}/.composer/cache

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # The SMTP server
      - "8025:8025" # The WEB UI
    networks:
      - network

  db:
    ports:
      # Expose the database in local environment so that we are able
      # to connect to it using Sequel Ace / Table Plus
      - ${DB_HOST_PORT:-3306}:3306
    volumes:
      - db:/var/lib/mysql

  nginx:
    ports:
      # The NGINX container is not running as root
      # which is why we can't listen on ports below
      # 1000.
      - ${NGINX_UNSECURE_PORT?}:8080
      - ${NGINX_SECURE_PORT?}:8443

  chrome:
    ports:
      - "7900:7900"