version: '3.9'

services:
  node:
    # Keep the node container running locally.
    # There are no long-running process defined as entrypoint for the container.
    # Keeping the container running saves as time for frequently run commands.
    # @see https://stackoverflow.com/a/55953120
    tty: true

  app:
    volumes:
      # We need to persist the host composer cache with the docker container.
      # Otherwise, each composer update will be extremely slow.
      - ${COMPOSER_CACHE_PATH?}:/home/${APP_USER_NAME?}/.composer/cache

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # WEB UI

  db:
    ports:
      # Expose the database in local environment so that we are able
      # to connect to it using Sequel Ace / Table Plus
      - "${DB_HOST_PORT:-3306}:3306"
    volumes:
      - db:/var/lib/mysql

  nginx:
    ports:
      - "${NGINX_UNSECURE_PORT?}:8080"
      - "${NGINX_SECURE_PORT?}:8443"
