version: '3.9'

#
# =================================================================
# Shared local volumes:
# =================================================================
#
# We need to create bind-mounts for project files for
# each container if we want to have live updates.
# Defining bind-mounts in one container only will not work,
# even though the files should in theory be connected through the shared volumes.
#
services:

  wp:
    volumes:
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle:${WP_CONTAINER_WP_APP_PATH?}/wp-content/bundle
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/component:${WP_CONTAINER_WP_APP_PATH?}/wp-content/component
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/plugin/foo-plugin:${WP_CONTAINER_WP_APP_PATH?}/wp-content/plugins/foo-plugin
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle/fortress-bundle/tests/cli/fortress-test-mu-plugin:${WP_CONTAINER_WP_APP_PATH?}/wp-content/mu-plugins/fortress-test-mu-plugin
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle/fortress-bundle/tests/cli/fortress-test-mu-plugin.php:${WP_CONTAINER_WP_APP_PATH?}/wp-content/mu-plugins/fortress-test-mu-plugin.php
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    extra_hosts:
      - host.docker.internal:host-gateway

  app:
    volumes:
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle:${APP_CONTAINER_WP_APP_PATH?}/wp-content/bundle
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/component:${APP_CONTAINER_WP_APP_PATH?}/wp-content/component
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/plugin/foo-plugin:${APP_CONTAINER_WP_APP_PATH?}/wp-content/plugins/foo-plugin
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle/fortress-bundle/tests/cli/fortress-test-mu-plugin:${APP_CONTAINER_WP_APP_PATH?}/wp-content/mu-plugins/fortress-test-mu-plugin
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle/fortress-bundle/tests/cli/fortress-test-mu-plugin.php:${APP_CONTAINER_WP_APP_PATH?}/wp-content/mu-plugins/fortress-test-mu-plugin.php
        # We need to persist the host composer cache with the docker container.
        # Otherwise, each composer update will be extremely slow.
      - ${COMPOSER_CACHE_PATH?}:/home/${APP_USER_NAME?}/.composer/cache
    build:
      args:
        - SSH_PASSWORD=${SSH_PASSWORD?}
    ports:
      - ${SSH_PORT?}:22
    extra_hosts:
      - host.docker.internal:host-gateway

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SMTP_PORT?}:1025
      - ${MAILHOG_UI_PORT?}:8025
    networks:
      - network

  db:
    ports:
      # Expose the database in local environment so that we are able
      # to connect to it using Sequel Ace / Table Plus
      - ${DB_PORT?}:3306
    volumes:
      - db:/var/lib/mysql

  nginx:
    volumes:
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/bundle:${WP_CONTAINER_WP_APP_PATH?}/wp-content/bundle
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/component:${WP_CONTAINER_WP_APP_PATH?}/wp-content/component
      - ${MONOREPO_ROOT_HOST?}/src/Snicco/plugin:${WP_CONTAINER_WP_APP_PATH?}/wp-content/plugin
    ports:
      # The NGINX container is not running as root
      # which is why we can't listen on ports below
      # 1000.
      - ${NGINX_UNSECURE_PORT?}:8080
      - ${NGINX_SECURE_PORT?}:8443