name: CI package registry

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4']
#        php: [ '8.1', '8.0', '7.4']
#        wp: [ '6.0', '5.9', '5.8']
        wp: [ '6.0']
    env:
      CACHE_PREFIX: snicco_1
      ENV: ci
      TAG: some-branch
      PHP_VERSION: ${{ matrix.php }}
      WP_VERSION: ${{ matrix.wp }}
      FORCE_RUN_IN_CONTAINER: 1

    steps:
      - uses: actions/checkout@v3

      - name: 'Set make env variables'
        run: |
          echo "APP_USER_NAME=$(id -un)" >> $GITHUB_ENV
          echo "APP_USER_ID=$(id -u)" >> $GITHUB_ENV
          echo "APP_GROUP_NAME=$(id -gn)" >> $GITHUB_ENV
          echo "APP_GROUP_ID=$(id -g)" >> $GITHUB_ENV

      - name: 'Install docker compose'
        run : |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins 
          curl -sSL https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-$(uname -m) -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version
          docker --version
          docker buildx version

      - name: 'Login to GitHub package registry'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Pull docker images'
        run: |
          make init
          make docker-pull || true

      - name: 'Start containers'
        run: |
          make docker-build
          make docker-up MODE=--detach

      - name: 'Restore QA cache'
        uses: actions/cache@v3
        with:
          path: /tmp/snicco-qa
          key: ${{ env.CACHE_PREFIX }}-qa-tools-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ env.CACHE_PREFIX }}-qa-tools-composer-

      - name: 'QA'
        if: ${{ matrix.php }} == '7.4' && ${{ matrix.wp }} == '6.0'
        run: |
          make build-codeception
          make docker-copy-vendor
          make composer-unused || true

#      - name: 'Source code tests: PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
#        run: |
#          make unit-tests
#
#      - name: 'Build plugins'
#        run: |
#          make build BUILD_VERSION=${{ github.sha }}
#          make copy-prod-plugins
#
#      - name: 'Build tests'
#        run: |
#          make cli-tests
#          make browser-tests

      - name: 'Push docker images to GitHub package registry'
        run: |
          make docker-push
