name: CI build and test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CACHE_PREFIX: snicco_1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        wp: [ '5.8', '5.9', '6.0' ]
    env:
      APP_IMAGE_NAME: snicco/app-ci-php${{ matrix.php }}
      WP_IMAGE_NAME: snicco/wp-ci-php${{ matrix.php }}-wp${{ matrix.wp }}
      NGINX_IMAGE_NAME: snicco/nginx-ci
      NODE_IMAGE_NAME: snicco/node-ci

    steps:
      - uses: actions/checkout@v3

      - name: 'Install docker'
        run : |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins 
          curl -sSL https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-$(uname -m) -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version
          docker --version
          docker buildx version

      - name: 'Restore cache'
        uses: actions/cache@v3
        with:
          path: /tmp/snicco-docker
          key: ${{ env.CACHE_PREFIX }}-php${{ matrix.php }}-wp${{ matrix.wp }}-${{ github.sha }}
          restore-keys: |
            ${{ env.CACHE_PREFIX }}-php${{ matrix.php }}-wp${{ matrix.wp }}-
            ${{ env.CACHE_PREFIX }}-

      - name: 'Load docker images'
        run: |
          docker image load < /tmp/snicco-docker/${{ env.APP_IMAGE_NAME }}.tar || true
          docker image load < /tmp/snicco-docker/${{ env.WP_IMAGE_NAME }}.tar || true
          docker image load < /tmp/snicco-docker/${{ env.NGINX_IMAGE_NAME }}.tar || true
          docker image load < /tmp/snicco-docker/${{ env.NODE_IMAGE_NAME }}.tar || true

      - name: 'Docker setup ${{ matrix.php }}, WP ${{ matrix.wp }}'
        run: |
          make init ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wp }}
          make docker-build ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wp }}
          make docker-up ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121 MODE=--detach PHP_VERSION=${{ matrix.php }} WP_VERSION=${{ matrix.wp }}

      - name: 'Save docker images'
        run: |
          mkdir -p /tmp/snicco-docker/snicco || true
          docker image save ${{ env.APP_IMAGE_NAME }} > /tmp/snicco-docker/${{ env.APP_IMAGE_NAME }}.tar
          docker image save ${{ env.WP_IMAGE_NAME }} > /tmp/snicco-docker/${{ env.WP_IMAGE_NAME }}.tar
          docker image save ${{ env.NGINX_IMAGE_NAME }} > /tmp/snicco-docker/${{ env.NGINX_IMAGE_NAME }}.tar
          docker image save ${{ env.NODE_IMAGE_NAME }} > /tmp/snicco-docker/${{ env.NODE_IMAGE_NAME }}.tar

      - name: 'Tests, PHP ${{ matrix.php }}, WP ${{ matrix.wp }}'
        run: |
          make unit-tests ENV=ci APP_USER_NAME=runner APP_USER_ID=1001 APP_GROUP_NAME=docker APP_GROUP_ID=121